export const ALL_COMMODITIES = [
  "Tomato",
  "Potato",
  "Onion",
  "Apple",
  "Banana",
  "Mango",
  "Orange",
  "Cucumber",
  "Carrot",
  "Spinach",
  "Rice",
  "Wheat",
  "Maize",
  "Oats",
  "Potato Chips",
  "Biscuits",
  "Bread",
  "Milk Powder",
  "Turmeric Powder",
  "Coffee Beans",
  "Peanuts",
  "Cashews",
  "Lentils",
  "Raisins",
  "Flour",
];

export const COMMODITY_METADATA = {
  Tomato: { category: "Fresh Vegetable", emoji: "🍅", respiration: "High" },
  Potato: { category: "Root Vegetable", emoji: "🥔", respiration: "Medium" },
  Onion: { category: "Bulb Vegetable", emoji: "🧅", respiration: "Low" },
  Apple: { category: "Fresh Fruit", emoji: "🍎", respiration: "Low" },
  Banana: { category: "Fresh Fruit", emoji: "🍌", respiration: "High" },
  Mango: { category: "Fresh Fruit", emoji: "🥭", respiration: "Medium" },
  Orange: { category: "Citrus Fruit", emoji: "🍊", respiration: "Medium" },
  Cucumber: { category: "Fresh Vegetable", emoji: "🥒", respiration: "High" },
  Carrot: { category: "Root Vegetable", emoji: "🥕", respiration: "Medium" },
  Spinach: { category: "Leafy Vegetable", emoji: "🥬", respiration: "Very High" },
  Rice: { category: "Grain", emoji: "🌾", respiration: "Low" },
  Wheat: { category: "Grain", emoji: "🌾", respiration: "Low" },
  Maize: { category: "Grain", emoji: "🌽", respiration: "Low" },
  Oats: { category: "Cereal Grain", emoji: "🥣", respiration: "Low" },
  "Potato Chips": { category: "Snack", emoji: "🥔", respiration: "Low" },
  Biscuits: { category: "Baked Snack", emoji: "🍪", respiration: "Low" },
  Bread: { category: "Bakery", emoji: "🍞", respiration: "Low" },
  "Milk Powder": { category: "Dairy Powder", emoji: "🥛", respiration: "Low" },
  "Turmeric Powder": { category: "Spice", emoji: "🧂", respiration: "Low" },
  "Coffee Beans": { category: "Beverage", emoji: "☕", respiration: "Low" },
  Peanuts: { category: "Nut", emoji: "🥜", respiration: "Low" },
  Cashews: { category: "Nut", emoji: "🥜", respiration: "Low" },
  Lentils: { category: "Pulse", emoji: "🍲", respiration: "Low" },
  Raisins: { category: "Dried Fruit", emoji: "🍇", respiration: "Low" },
  Flour: { category: "Milled Grain", emoji: "🌾", respiration: "Low" },
};

export const DEFAULT_VALUES = {
  Tomato: { shelfLife: 15, temperature: 5, humidity: 90, storageType: "Chilled", transportation: "Refrigerated" },
  Potato: { shelfLife: 30, temperature: 10, humidity: 90, storageType: "Chilled", transportation: "Ambient" },
  Onion: { shelfLife: 60, temperature: 25, humidity: 65, storageType: "Ambient", transportation: "Ambient" },
  Apple: { shelfLife: 90, temperature: 2, humidity: 90, storageType: "Chilled", transportation: "Refrigerated" },
  Banana: { shelfLife: 14, temperature: 13, humidity: 90, storageType: "Ambient", transportation: "Ambient" },
  Mango: { shelfLife: 21, temperature: 10, humidity: 90, storageType: "Chilled", transportation: "Refrigerated" },
  Orange: { shelfLife: 45, temperature: 5, humidity: 90, storageType: "Chilled", transportation: "Refrigerated" },
  Cucumber: { shelfLife: 14, temperature: 10, humidity: 95, storageType: "Chilled", transportation: "Refrigerated" },
  Carrot: { shelfLife: 45, temperature: 4, humidity: 95, storageType: "Chilled", transportation: "Refrigerated" },
  Spinach: { shelfLife: 7, temperature: 2, humidity: 95, storageType: "Chilled", transportation: "Refrigerated" },
  Rice: { shelfLife: 365, temperature: 25, humidity: 60, storageType: "Ambient", transportation: "Ambient" },
  Wheat: { shelfLife: 365, temperature: 25, humidity: 60, storageType: "Ambient", transportation: "Ambient" },
  Maize: { shelfLife: 365, temperature: 25, humidity: 60, storageType: "Ambient", transportation: "Ambient" },
  Oats: { shelfLife: 365, temperature: 20, humidity: 60, storageType: "Ambient", transportation: "Ambient" },
  "Potato Chips": { shelfLife: 180, temperature: 25, humidity: 50, storageType: "Ambient", transportation: "Ambient" },
  Biscuits: { shelfLife: 180, temperature: 25, humidity: 50, storageType: "Ambient", transportation: "Ambient" },
  Bread: { shelfLife: 7, temperature: 25, humidity: 60, storageType: "Ambient", transportation: "Ambient" },
  "Milk Powder": { shelfLife: 180, temperature: 20, humidity: 40, storageType: "Ambient", transportation: "Ambient" },
  "Turmeric Powder": { shelfLife: 365, temperature: 25, humidity: 60, storageType: "Ambient", transportation: "Ambient" },
  "Coffee Beans": { shelfLife: 365, temperature: 20, humidity: 60, storageType: "Ambient", transportation: "Ambient" },
  Peanuts: { shelfLife: 180, temperature: 20, humidity: 60, storageType: "Ambient", transportation: "Ambient" },
  Cashews: { shelfLife: 365, temperature: 20, humidity: 60, storageType: "Ambient", transportation: "Ambient" },
  Lentils: { shelfLife: 365, temperature: 25, humidity: 60, storageType: "Ambient", transportation: "Ambient" },
  Raisins: { shelfLife: 180, temperature: 20, humidity: 60, storageType: "Ambient", transportation: "Ambient" },
  Flour: { shelfLife: 180, temperature: 20, humidity: 60, storageType: "Ambient", transportation: "Ambient" },
};

export const getDefaults = (name) => {
  return (
    DEFAULT_VALUES[name] || {
      shelfLife: 15,
      temperature: 5,
      humidity: 90,
      storageType: "Chilled",
      transportation: "Refrigerated",
    }
  );
};
